name: Deploy Next.js (static) to cPanel via FTP

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    env:
      NEXT_TELEMETRY_DISABLED: 1
      # Put any build-time envs you need here or define as repo secrets:
      # NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
          cache: npm
          cache-dependency-path: apps/web/package-lock.json

      - run: npm ci
      - run: npm run build
      - run: npm run export  # creates apps/web/out

      - name: Deploy via FTP to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}     # e.g. ftp.yourdomain.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || 21 }}
          protocol: ftps
          local-dir: apps/web/out/
          # Adjust remote dir; often /public_html or /public_html/subdir
          server-dir: ${{ secrets.CPANEL_FTP_REMOTE_DIR || '/public_html/' }}
          # Optional: keep uploads, etc.
          exclude: |
            **/.git*
            **/.DS_Store
